theme: minima
url: "https://a-cy99.github.io"
baseurl: "/MyLittleBVB"      
title: "미정의 돌공군"       # 사이트 타이틀
description: "돌공군의 편향된 시선"  # 
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
